fix: Rename optuna.py to optuna_example.py
- the filename "optuna.py" is shadowing the "optuna" module and will crash with a circular import error e.g. AttributeError: partially initialized module 'optuna' has no attribute 'optuna' (most likely due to a circular import).